### ISSUE TITLE
How to get the data? or nor available

### ISSUE THREAD

**Issue by Ray-X-hi** [hassonlab/247-data#1]
So, is there any data available here if possible, it's been more than a year since the article was published.

**Comment by hvgazula** [comment]
Hello @Ray-X-hi This is still under consideration as there are some decisions to be made. However, you may want to check https://eval.ai/web/challenges/challenge-page/2099/overview for the closest counterpart.

**Comment by Ray-X-hi** [comment]
OK, I see, Thanks a lot!
